node {
    def commit_id
    stage('Preparation') {
        checkout scm  // this command will git clone the repository 
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readfile(".git/commit-id").trim()
    }
    stage('test'){
        nodejs('nodeJSInstallationName', 'nodejs'){
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }
}