language: generic
sudo: required
services:
  - docker

before_install :
  - docker build -t iliass373/Deployement-Front-end-ReactJS- -f Dockerfile.dev .

script:
  - docker run -e CI=true iliass373/Deployement-Front-end-ReactJS- npm run test 