version: '3'
services: 
  react_js:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3001:3000"
    volumes:
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ["npm", "run", "test"]